server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false

feign:
  hystrix:
    enabled: true


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000




spring:
  main:
    allow-bean-definition-overriding: true
