server:
  port: 7001
# eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false # 表示是否从Eureka Server上获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka