server:
  port: 6001
management.port: 6002
spring:
  application:
    name: TURBINE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false # \u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka Server\u4E0A\uFF0C\u9ED8\u8BA4\u4E3Atrue
    fetch-registry: false # \u8868\u793A\u662F\u5426\u4ECEEureka Server\u4E0A\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue
turbine:
  app-config: eureka-client
  combine-host-port: true



