server:
  port: 6001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false

zuul:
  routes:
    api-8005:
      path: /api-8005/**
      serviceId: eureka-client5
    api-8001:
      path: /api-8001/**
      serviceId: eureka-client
